[package]
name = "windows-orphan-cleaner"
version = "0.1.0"
edition = "2024"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
cleaner-core = { path = "../crates/cleaner-core" }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }

